package Data

import Chat.ExprTree
import Data.MessageService.*
import Utils.{IdGenerator, LongIdGenerator}
import scalatags.Text.Frag

object MessageService:
  type Username = String
  type MsgContent = Frag

trait MessageService:
  /** Retrieve the latest N added messages
    * @param n
    *   The number of message to retrieve
    * @return
    *   The content of the messages and their senders
    */
  def getLatestMessages(n: Int): Seq[(Username, MsgContent)]

  /** Add a message to the history
    * @param sender
    *   The username of the sender
    * @param msg
    *   The content of the message
    * @param mention
    *   The name if it exists of the user mentioned at the start of the message
    *   with an '@'. For example the message "@Julian Hello" mentions "Julian"
    * @param exprType
    *   If the message is to the bot, the type of the query
    * @param replyToId
    *   If the message is a reply to another message, the id of the other
    *   message. Used for example, when the bot answers to a query
    * @return
    *   the unique id of the added message (generated by a method of your
    *   choice)
    */
  def add(
      sender: Username,
      msg: MsgContent,
      mention: Option[Username] = None,
      exprType: Option[ExprTree] = None,
      replyToId: Option[Long] = None,
  ): Long

  /** Deletes all the stored messages
    */
  def deleteHistory(): Unit

class MessageImpl extends MessageService:
  import MessageImpl.*

  private var messages: Seq[StoredMessage] = Nil
  private val idGen: IdGenerator[Long] = LongIdGenerator()

  override def add(
      sender: Username,
      msg: MsgContent,
      mention: Option[Username] = None,
      exprType: Option[ExprTree] = None,
      replyToId: Option[Long] = None,
  ): Long =
    val storedMsg =
      StoredMessage(idGen.nextId(), sender, msg, mention, exprType, replyToId)
    messages = storedMsg +: messages
    storedMsg.id

  override def getLatestMessages(n: Int): Seq[(Username, MsgContent)] =
    Seq.from(
      messages
        .take(n)
        .map { case StoredMessage(_, sender, msg, _, _, _) => (sender, msg) }
        .reverse,
    )

  override def deleteHistory(): Unit =
    messages = Nil
    idGen.reset()

object MessageImpl:
  private case class StoredMessage(
      id: Long,
      sender: Username,
      msg: MsgContent,
      mention: Option[Username],
      exprType: Option[ExprTree],
      replyToId: Option[Long],
  )
